### ISSUE TITLE
data visualization

### ISSUE THREAD

**Issue by darkbtf** [cofacts/rumors-db#9]
* **被詢問度排序**
* **詢問時間分佈** 
* 謠言生命週期 (詢問次數-天數、回答數-天數)
* 謠言分類器 (是謠言、非謠言、不用處理)
* 最久閒置的謠言

**Comment by MrOrz** [comment]
Currently the open data is processed manually, and here is the result: https://datastudio.google.com/embed/reporting/18J8jZYumsoaCPBk9bdRd97GKvi_W5v-r/page/ckUQ

To facilitate the auto-sync between opendata source on github and Google data studio, we may need to implement a data studio connector:

- Referene: https://developers.google.com/datastudio/connector/build (on google apps script)
- Unzip: Utilities.unzip https://stackoverflow.com/questions/45284798/using-google-app-script-unzip-a-file-from-google-drive

**Comment by MrOrz** [comment]
A connector is no longer needed, the visualizations are connected to google cloud storage open data CSV files now. Closing.
